# Generated by Django 4.1.4 on 2022-12-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerForm', '0002_alter_emotion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerad',
            name='webpage_raw_content',
            field=models.TextField(blank=True),
        ),
    ]
